### ISSUE TITLE
Error starting Tomcat context

### ISSUE THREAD

**Issue by nuno-miranda-loba** [rmpt/citizen-card-reader#1]
@rmpt Olá! antes de mais obrigado pela partilha deste repositório!

Estou a utilizar um Mac M1 e java na versão 19, segui os passos que indica na documentação mas obtenho sempre este erro:

13:43:43.878 [main] INFO  c.r.c.r.a.CitizenCardReaderApiApplicationKt MDC= - No active profile set, falling back to 1 default profile: "default"
13:43:44.620 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer MDC= - Tomcat initialized with port(s): 8080 (http)
13:43:44.626 [main] INFO  o.a.coyote.http11.Http11NioProtocol MDC= - Initializing ProtocolHandler ["http-nio-8080"]
13:43:44.627 [main] INFO  o.a.catalina.core.StandardService MDC= - Starting service [Tomcat]
13:43:44.627 [main] INFO  o.a.catalina.core.StandardEngine MDC= - Starting Servlet engine: [Apache Tomcat/9.0.71]
13:43:44.669 [main] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] MDC= - Initializing Spring embedded WebApplicationContext
13:43:44.669 [main] INFO  o.s.b.w.s.c.ServletWebServerApplicationContext MDC= - Root WebApplicationContext: initialization completed in 761 ms
13:43:44.686 [main] INFO  c.r.c.reader.peidlib.PteidlibLoader MDC= - Loading PTEID library....
13:43:44.686 [main] INFO  c.r.c.r.p.setup.PteidSetupFactory MDC= - MacOs Operating System detected
13:43:44.687 [main] INFO  c.r.c.r.p.setup.PteidSetupMacOs MDC= - Using installed lib '/usr/local/lib/libpteidlibj.2.0.0.dylib'
13:43:44.688 [main] ERROR o.s.b.w.e.tomcat.TomcatStarter MDC= - Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'mainConfig': Invocation of init method failed; nested exception is java.lang.UnsatisfiedLinkError: Can't load library: /usr/local/lib/libpteidlibj.2.0.0.dylib
13:43:44.701 [main] INFO  o.a.catalina.core.StandardService MDC= - Stopping service [Tomcat]
13:43:44.704 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext MDC= - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
13:43:44.708 [main] INFO  o.s.b.a.l.ConditionEvaluationReportLoggingListener MDC= - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
13:43:44.719 [main] ERROR o.s.boot.SpringApplication MDC= - Application run failed

Já testei num windows e funciona mas no mac não... qual acha que pode ser o problema ?
Obrigado!

**Comment by rmpt** [comment]
Tem a aplicação autenticação.gov instalada? Se sim, por favor execute o comando seguinte e partilhe aqui:
`ls -l /usr/local/lib/ | grep pteid`

**Comment by nuno-miranda-loba** [comment]
tenho sim 

nunomiranda@MBP-de-Nuno-2 ~ % ls -l /usr/local/lib/ | grep pteid
-rwxr-xr-x   1 root  wheel  2284304  2 Jan 17:17 libpteidapplayer.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       28 12 Mar 21:52 libpteidapplayer.2.0.dylib -> libpteidapplayer.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       28 12 Mar 21:52 libpteidapplayer.2.dylib -> libpteidapplayer.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       28 12 Mar 21:52 libpteidapplayer.dylib -> libpteidapplayer.2.0.0.dylib
-rwxr-xr-x   1 root  wheel   272272  2 Jan 17:17 libpteidcardlayer.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       29 12 Mar 21:52 libpteidcardlayer.2.0.dylib -> libpteidcardlayer.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       29 12 Mar 21:52 libpteidcardlayer.2.dylib -> libpteidcardlayer.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       29 12 Mar 21:52 libpteidcardlayer.dylib -> libpteidcardlayer.2.0.0.dylib
-rwxr-xr-x   1 root  wheel   264208  2 Jan 17:17 libpteidcommon.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       26 12 Mar 21:52 libpteidcommon.2.0.dylib -> libpteidcommon.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       26 12 Mar 21:52 libpteidcommon.2.dylib -> libpteidcommon.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       26 12 Mar 21:52 libpteidcommon.dylib -> libpteidcommon.2.0.0.dylib
-rwxr-xr-x   1 root  wheel    77248  2 Jan 17:17 libpteiddialogsQT.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       29 12 Mar 21:52 libpteiddialogsQT.2.0.dylib -> libpteiddialogsQT.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       29 12 Mar 21:52 libpteiddialogsQT.2.dylib -> libpteiddialogsQT.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       29 12 Mar 21:52 libpteiddialogsQT.dylib -> libpteiddialogsQT.2.0.0.dylib
-rwxr-xr-x   1 root  wheel   387168  2 Jan 17:17 libpteidlib.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       23 12 Mar 21:52 libpteidlib.2.0.dylib -> libpteidlib.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       23 12 Mar 21:52 libpteidlib.2.dylib -> libpteidlib.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       23 12 Mar 21:52 libpteidlib.dylib -> libpteidlib.2.0.0.dylib
-rwxr-xr-x   1 root  wheel   671792  2 Jan 17:17 libpteidlibj.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       24 12 Mar 21:52 libpteidlibj.2.0.dylib -> libpteidlibj.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       24 12 Mar 21:52 libpteidlibj.2.dylib -> libpteidlibj.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       24 12 Mar 21:52 libpteidlibj.dylib -> libpteidlibj.2.0.0.dylib
-rwxr-xr-x   1 root  wheel   134656  2 Jan 17:17 libpteidpkcs11.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       26 12 Mar 21:52 libpteidpkcs11.2.0.dylib -> libpteidpkcs11.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       26 12 Mar 21:52 libpteidpkcs11.2.dylib -> libpteidpkcs11.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       26 12 Mar 21:52 libpteidpkcs11.dylib -> libpteidpkcs11.2.0.0.dylib
drwxr-xr-x   3 root  wheel       96  2 Jan 17:17 pteid_jni

**Comment by rmpt** [comment]
Estranho, tem os ficheiros necessários mas parece que não estão a ser encontrados. Está a correr a app no mesmo terminal onde correu o comando que lhe indiquei? Terei de ver com mais detalhe o que se passa, mas pelo que vejo deveria funcionar.

**Comment by nuno-miranda-loba** [comment]
nao, corri o comando num terminal novo, mas agora corri na pasta do projeto 

nunomiranda@MBP-de-Nuno-2 citizen-card-reader-0.1 % ls -l /usr/local/lib/ | grep pteid
-rwxr-xr-x   1 root  wheel  2284304  2 Jan 17:17 libpteidapplayer.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       28 12 Mar 21:52 libpteidapplayer.2.0.dylib -> libpteidapplayer.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       28 12 Mar 21:52 libpteidapplayer.2.dylib -> libpteidapplayer.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       28 12 Mar 21:52 libpteidapplayer.dylib -> libpteidapplayer.2.0.0.dylib
-rwxr-xr-x   1 root  wheel   272272  2 Jan 17:17 libpteidcardlayer.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       29 12 Mar 21:52 libpteidcardlayer.2.0.dylib -> libpteidcardlayer.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       29 12 Mar 21:52 libpteidcardlayer.2.dylib -> libpteidcardlayer.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       29 12 Mar 21:52 libpteidcardlayer.dylib -> libpteidcardlayer.2.0.0.dylib
-rwxr-xr-x   1 root  wheel   264208  2 Jan 17:17 libpteidcommon.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       26 12 Mar 21:52 libpteidcommon.2.0.dylib -> libpteidcommon.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       26 12 Mar 21:52 libpteidcommon.2.dylib -> libpteidcommon.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       26 12 Mar 21:52 libpteidcommon.dylib -> libpteidcommon.2.0.0.dylib
-rwxr-xr-x   1 root  wheel    77248  2 Jan 17:17 libpteiddialogsQT.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       29 12 Mar 21:52 libpteiddialogsQT.2.0.dylib -> libpteiddialogsQT.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       29 12 Mar 21:52 libpteiddialogsQT.2.dylib -> libpteiddialogsQT.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       29 12 Mar 21:52 libpteiddialogsQT.dylib -> libpteiddialogsQT.2.0.0.dylib
-rwxr-xr-x   1 root  wheel   387168  2 Jan 17:17 libpteidlib.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       23 12 Mar 21:52 libpteidlib.2.0.dylib -> libpteidlib.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       23 12 Mar 21:52 libpteidlib.2.dylib -> libpteidlib.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       23 12 Mar 21:52 libpteidlib.dylib -> libpteidlib.2.0.0.dylib
-rwxr-xr-x   1 root  wheel   671792  2 Jan 17:17 libpteidlibj.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       24 12 Mar 21:52 libpteidlibj.2.0.dylib -> libpteidlibj.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       24 12 Mar 21:52 libpteidlibj.2.dylib -> libpteidlibj.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       24 12 Mar 21:52 libpteidlibj.dylib -> libpteidlibj.2.0.0.dylib
-rwxr-xr-x   1 root  wheel   134656  2 Jan 17:17 libpteidpkcs11.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       26 12 Mar 21:52 libpteidpkcs11.2.0.dylib -> libpteidpkcs11.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       26 12 Mar 21:52 libpteidpkcs11.2.dylib -> libpteidpkcs11.2.0.0.dylib
lrwxr-xr-x   1 root  wheel       26 12 Mar 21:52 libpteidpkcs11.dylib -> libpteidpkcs11.2.0.0.dylib
drwxr-xr-x   3 root  wheel       96  2 Jan 17:17 pteid_jni
nunomiranda@MBP-de-Nuno-2 citizen-card-reader-0.1 % 

PS: Se tivesse disponibilidade para um meet agradecia imenso :)

**Comment by rmpt** [comment]
já tentou correr a aplicação como root? `sudo java -jar citizen-card-reader-api.jar`

**Comment by nuno-miranda-loba** [comment]
Sim tentei, dá sempre o mesmo erro...
 ERROR o.s.b.w.e.tomcat.TomcatStarter MDC= - Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'mainConfig': Invocation of init method failed; nested exception is java.lang.UnsatisfiedLinkError: Can't load library: /usr/local/lib/libpteidlibj.2.0.0.dylib

**Comment by rmpt** [comment]
Qual a versão da aplicação autenticacao.gov que tem instalada?

**Comment by nuno-miranda-loba** [comment]
Tenho a Versão 3.9.1

<img width="777" alt="image" src="https://user-images.githubusercontent.com/38323786/225560213-bfe0f9ae-918b-4f1f-8dce-ac5f99043698.png">

**Comment by Tragio** [comment]
Olá @rmpt e @nuno-miranda-loba 👋 

Antes de mais muito obrigado @rmpt por partilhares este projeto 🙏 

Estava a ter o mesmo problema e depois de algum debug percebi que era isto:

`'/usr/local/lib/libpteidlibj.2.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))`

Instalei o Java 8 x86 no Mac e funcionou. O problema é que o JDK 17 e 21 não deixam instalar x86 em Mac com M chips.

Quando compilaste aplicação estavas a usar um Mac? 🤔 

Não sei se haverá alguma forma de contornar isto ou obrigar aplicação a correr sempre em x86 ou a compilar em x86. Torna-se complicado dizer ao utilizadores para removerem um Java e terem de instalar outro 😅 

Tentei:
`arch -x86_64 java -jar ...`
`arch -x86_64 ./gradlew clean bootJar`

Mas não consegui, só mesmo instalando o Java 8 com x86.

A minha área também não é Java por isso pode ter-me falhado algo 🤔 

Muito obrigado 😃

**Comment by rmpt** [comment]
Olá @Tragio , obrigado pelo feedback.
Sobre o teu erro, creio estar relacionado com a versão da app cartão de cidadão que tens intalada, pelo menos é o que o erro diz:
`'/usr/local/lib/libpteidlibj.2.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))`

`libpteidlibj.2.0.0.dylib` é a biblioteca do cartão de cidadão, instalaste a versão certa? Compativel com arm64? Pergunto isto pois o jar, supostamente, corre em qualquer OS desde que tenha o JVM instalado.

Valida que tens a versão do cartão de cidadão certa e tenta de novo com a versão do java mais recente, as arquitecturas do java e do cartão de cidadão devem estar alinhadas. Se não funcionar, podes sempre tentar compilar e gerar o jar no teu pc, mas creio que não fará diferença.

**Comment by Tragio** [comment]
Olá @rmpt 👋

Foi lançada uma nova versão na semana passada que já inclui compatibilidade com ARM. Por isso, este problema deve estar resolvido 🙏

Muito obrigado!

**Comment by rmpt** [comment]
ok, experimenta e depois diz-me se funcinou por favor.

**Comment by rmpt** [comment]
@Tragio alguma novidade?

**Comment by Tragio** [comment]
@rmpt depois da última versão, tudo impecável. Obrigado 🙏
